### ISSUE TITLE
upgrade action to use node 20

### ISSUE THREAD

**Issue by phun-ky** [jayqi/failed-build-issue-action#104]
```
Notify failed build
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: jayqi/failed-build-issue-action@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

ref: https://github.com/phun-ky/speccer/actions/runs/7937582620

**Comment by jayqi** [comment]
Closed by https://github.com/jayqi/failed-build-issue-action/commit/79a8fa2aa2cbe249a09b382014d2f366628c8bb9 and released as [v1.2.0](https://github.com/jayqi/failed-build-issue-action/releases/tag/v1.2.0).
